### ISSUE TITLE
[Wyvern] Wrong picture

### ISSUE THREAD

**Issue by eulchen05** [gwentcards/gwentcards.github.io#26]
**Platform**: PC
**Game version**: v 4.04

**Card name**: Wyvern
**Issue**: Under the card "Wyvern" is the picture of the Werewolf card

love the site. very helpful

**Comment by vzx** [comment]
Thanks a lot for reporting! Sloppy that this issue existed for years already without me noticing. I fixed it, but it might take a while to show up due to caching (ctrl+refresh might help).

**Comment by eulchen05** [comment]
Happy to help! Made an account just to report this and my other issue since I like the site so much.
