### ISSUE TITLE
[Card] torrential rain

### ISSUE THREAD

**Issue by TitaniumAcolyte** [gwentcards/gwentcards.github.io#3]
**Platform**: PC / PS4 / Xbox / Switch / etc
**Game version**: v1.60

**Card name**: torrential rain card
**Issue**: your guide only shows that there are two torrential Gwent cards when in fact there are three. The first is part of the base set you start with and the other two are achieved randomly by playing NPCs. Therefore your guide should show 1 of 3, 2 of 3 and 3 of 3, instead of just the two that it now shows. Here’s two additional links showing that there should in fact be 3 torrential rain neutral cards listed https://witcher.fandom.com/wiki/Torrential_Rain_(gwent_card)
https://game8.co/games/Witcher3/archives/276461

**Comment by vzx** [comment]
Thanks for taking the time to report this issue @TitaniumAcolyte! Strange that I missed it when I was validating the list while playing the game. I will update the card list and add it later today.

**Comment by vzx** [comment]
I updated the cards information and added the 3rd Torrential Rain, so now it's in the list!

I did a quick check in game, and it looks like there's an additional Clear Weather too that I had missed apparently, so I have added that too.

Thanks once again for the report!
